### ISSUE TITLE
Is there any guideline for this tool?

### ISSUE THREAD

**Issue by gordonpro** [NativeScript/android-dts-generator#1]
I want to use this tool to generage Android23.d.ts. Then replace my project android17.d.ts that download from https://github.com/NativeScript/NativeScript/blob/master/android17.d.ts

**Comment by atanasovg** [comment]
Hello,

We are currently polishing it and fixing some issues. Once ready we will update the README with instructions how to take advantage of it.

**Comment by georgeedwards** [comment]
I agree that it would be nice to generate our own docs. Also worth noting the issue [here](https://github.com/NativeScript/NativeScript/issues/2295) which will see definition files for every 17+ API shipped with the `tns-core-modules` package

**Comment by Plamen5kov** [comment]
hi @georgeedwards,
No documentation yet, but in case you're interested in testing it out, there is a -help command.
How to run:

```
java -jar dts-generator.jar -help
```

**Comment by roblav96** [comment]
I'm very excited to test this out :D

**Comment by roblav96** [comment]
How do you get the `dts-generator.jar` to build?

or, where is the `dts-generator.jar` file?

**Comment by Plamen5kov** [comment]
`cd android-dts-generator>/dts-generator/`
`./gradew jar`
result jar is in into `android-dts-generator/dts-generator/build/libs/dts-generator.jar`

**Comment by roblav96** [comment]
That's what I ended up doing before i deleted the comment.

i notice the only way to get this working with a .jar is if I also include Android.jar

**Comment by petekanev** [comment]
@roblav96 @gordonpro README was updated. Feel free to check out the generator. Suggestions, Contributions, and overall feedback of the tool are welcome. It's far from a finished state, but it should be stable enough to work in the general cases.

**Comment by justgeek** [comment]
Did anyone get this error while building SDK 23? 

` org.nativescript.widgets.d.ts(28,41): error TS2315: Type 'ArrayList' is not generic.`

**Comment by petekanev** [comment]
@justgeek please either open a new issue with details about the problems you are experiencing, or open a new post on the official forums to ask nativescript-related questions.

What arguments did you start the generator with?

**Comment by roblav96** [comment]
@justgeek I did a presentation on how to use this tool [Fall In Love With Native APIs](https://www.youtube.com/watch?v=zCdbrkmvdVI)
