### ISSUE TITLE
Error in generated .d.ts file

### ISSUE THREAD

**Issue by sarvagayatri** [NativeScript/android-dts-generator#20]
I generated d.ts file for java.util, and paytm android sdk, both giving few errors in the file

> app/item/android.d.ts(18,8): error TS2300: Duplicate identifier 'javalangThrowable'.

app/item/android.d.ts(18,28): error TS2503: Cannot find namespace 'java'.

app/item/android.d.ts(133,22): error TS2503: Cannot find namespace 'java'.
app/item/android.d.ts(153,26): error TS2503: Cannot find namespace 'android'.
app/item/android.d.ts(154,30): error TS2503: Cannot find namespace 'android'.
app/item/android.d.ts(155,35): error TS2503: Cannot find namespace 'android'.
app/item/android.d.ts(181,32): error TS2503: Cannot find namespace 'android'.

app/item/android.d.ts(283,24): error TS2503: Cannot find namespace 'java'.
app/item/android.d.ts(284,29): error TS2503: Cannot find namespace 'java'.
app/item/android.d.ts(340,28): error TS2503: Cannot find namespace 'java'.
app/item/android.d.ts(362,31): error TS2503: Cannot find namespace 'android'.
app/item/android.d.ts(363,32): error TS2503: Cannot find namespace 'android'.
app/item/android.d.ts(364,39): error TS2503: Cannot find namespace 'android'.
app/item/android.d.ts(365,33): error TS2503: Cannot find namespace 'android'.
app/item/items.component.ts(113,24): error TS2339: Property 'java' does not exist on type 'typeof com'.

app/item/java-util/java.util.d.ts(2,8): error TS2300: Duplicate identifier 'javalangThrowable'.

app/item/java-util/java.util.d.ts(2,28): error TS2503: Cannot find namespace 'java'.
app/item/java-util/java.util.d.ts(16,28): error TS2503: Cannot find namespace 'java'.
app/item/java-util/java.util.d.ts(69,22): error TS2503: Cannot find namespace 'java'.
app/item/java-util/java.util.d.ts(85,25): error TS2503: Cannot find namespace 'java'.
app/item/java-util/java.util.d.ts(86,29): error TS2503: Cannot find namespace 'java'.
app/item/java-util/java.util.d.ts(106,29): error TS2503: Cannot find namespace 'java'.
app/item/java-util/java.util.d.ts(107,28): error TS2503: Cannot find namespace 'java'.

app/item/java-util/java.util.d.ts(108,29): error TS2503: Cannot find namespace 'java'.

TypeScript compiler failed with exit code 1

**Comment by mast3rd3mon** [comment]
what is the actual fix for this? i am having the same issue when i try to use this tool

**Comment by vtrifonov** [comment]
@mast3rd3mon are you using the latest version of the tool? Can you provide what typings you are trying to generate (and what arguments you're passing) in order to reproduce the issue?

**Comment by mast3rd3mon** [comment]
yeah i am using the latest, im trying to generate the typings for the zebra emdk. i managed to sort my issue by ignoring the smaller generated  file and using the one from tns-platform-declarations
