### ISSUE TITLE
some classes are missing there parent class

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/android-dts-generator#44]
building typings for androidx :
```gradle
testCompileOnly  "com.google.android.material:material:1.0.0"
```
then using 
```
java -jar build/libs/dts-generator.jar --skip-declarations -input dts-generator/jar-files
```

Some genearted classes are missing their parent class. Example ```com.google.android.material.textfield.TextInputLayout``` or ```com.google.android.material.textfield.TextInputEditText```

If you fix it by adding the extends you end up with some incompatible method declarations compared to parent class.

**Comment by farfromrefug** [comment]
Actually figured out that it is because the dts generator do not see the "android declarations". How can i make it see it?

**Comment by vtrifonov** [comment]
You need to pass supper class jars https://github.com/NativeScript/android-dts-generator#complex-typings-generation e.g.:
```
java -jar build/libs/dts-generator.jar --skip-declarations -input dts-generator/jar-files -super ${ANDROID_HOME}/platforms/android-17/android.jar
```
As an example how we generate the typings used in the **tns-platform-declarations** you can see in the [Makefile](https://github.com/NativeScript/android-dts-generator/blob/master/Makefile).

**Comment by farfromrefug** [comment]
@vtrifonov thank you so much! And thank you for the Makefile. Will apply the same to my module
