### ISSUE TITLE
Check for changed method signatures in inherited types

### ISSUE THREAD

**Issue by atanasovg** [NativeScript/android-dts-generator#5]
We do not need to generate entries for methods in inherited types if the signature hasn't changed. For example:

```
class A {
    public void method1() {
    }
}

class B extends A {
    @Override
    public method1() {
        super.method1();
        // extended logic
    }
}
```

In the above case we do not need to generate signature for `method1` in `class B`. This will improve the size of the generated definitions.

**Comment by petekanev** [comment]
All methods a class inherits and/or implements with unique signatures will only be written once per class as of #11
