### ISSUE TITLE
Add an option to select for a single, self-contained file vs. multiple files

### ISSUE THREAD

**Issue by atanasovg** [NativeScript/android-dts-generator#6]
The option with multiple definition files makes it harder to integrate with TS projects. My suggestion is to enable generation of single file with all the types and make it the default option. We may add a command-line arg that switches between the two approaches.

**Comment by Plamen5kov** [comment]
fixed with: https://github.com/NativeScript/android-dts-generator/pull/7
- flag `-generate-multiple` can be passed to the dts-generator.jar, or one file will be generated by default.
